### pakistan home page
POST https://api.openai.com/v1/chat/completions HTTP/1.1
Accept-Language: zh-CN;0.9
Content-Type: application/json
Authorization: Bearer --

{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "user",
      "content": "请介绍下北京烤鸭吧"
    }
  ],
  "temperature": 0.7
}

### pakistan home page
POST https://api.openai.com/v1/images/generations HTTP/1.1
Accept-Language: zh-CN;0.9
Content-Type: application/json
Authorization: Bearer --

{
  "prompt": "来一只花白的小猫",
  "n": 2,
  "size": "1024x1024"
}